# Tensor基础操作

In [13]:
import torch

In [14]:
x = torch.empty(5, 3)
x

tensor([[4.9592e-39, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39]])

In [15]:
x_rand = torch.rand(5, 3)
x_rand

tensor([[0.6593, 0.1664, 0.9731],
        [0.3485, 0.0918, 0.0183],
        [0.3317, 0.6910, 0.2603],
        [0.5461, 0.9457, 0.5383],
        [0.6342, 0.4578, 0.0190]])

In [16]:
x_long = torch.zeros(5, 3, dtype=torch.long)
x_long

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [17]:
x = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float) # 根据类型创建
x

tensor([1., 2., 3., 4., 5.])

In [18]:
x.shape

torch.Size([5])

In [19]:
x.size()

torch.Size([5])

In [22]:
# 可做加减法
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [23]:
x + y

tensor([[1.0350, 1.0788, 0.6852],
        [0.5224, 0.5999, 0.8488],
        [0.7579, 0.9771, 0.9597],
        [1.2450, 1.0233, 1.2771],
        [1.2689, 0.7598, 0.9600]])

In [24]:
# 这样也行
x.add(y)

tensor([[1.0350, 1.0788, 0.6852],
        [0.5224, 0.5999, 0.8488],
        [0.7579, 0.9771, 0.9597],
        [1.2450, 1.0233, 1.2771],
        [1.2689, 0.7598, 0.9600]])

In [25]:
# 这样也行
torch.add(x, y)

tensor([[1.0350, 1.0788, 0.6852],
        [0.5224, 0.5999, 0.8488],
        [0.7579, 0.9771, 0.9597],
        [1.2450, 1.0233, 1.2771],
        [1.2689, 0.7598, 0.9600]])

In [29]:
torch.add(x, y, out=y)

tensor([[2.5609, 2.5180, 1.8447],
        [1.4981, 1.4564, 1.8826],
        [2.2429, 2.8257, 2.6109],
        [3.1269, 2.8549, 3.0317],
        [3.0638, 1.9175, 2.1335]])

In [31]:
y

tensor([[2.5609, 2.5180, 1.8447],
        [1.4981, 1.4564, 1.8826],
        [2.2429, 2.8257, 2.6109],
        [3.1269, 2.8549, 3.0317],
        [3.0638, 1.9175, 2.1335]])

In [33]:
# 索引功能
x = torch.rand(5, 3)
y = x[:, 1]
print(x)
print(y)

tensor([[0.3654, 0.4571, 0.2273],
        [0.0126, 0.1949, 0.8327],
        [0.5999, 0.3840, 0.8391],
        [0.9840, 0.6709, 0.9550],
        [0.3656, 0.6259, 0.7896]])
tensor([0.4571, 0.1949, 0.3840, 0.6709, 0.6259])


In [38]:
# 也可以改变形状
y = x.view(-1, 5)
y

tensor([[0.3654, 0.4571, 0.2273, 0.0126, 0.1949],
        [0.8327, 0.5999, 0.3840, 0.8391, 0.9840],
        [0.6709, 0.9550, 0.3656, 0.6259, 0.7896]])

In [39]:
# 注意 view() 返回的新tensor与源tensor共享内存(其实是同一一个tensor),也即更更改其中的一一个,另  外一一个也会跟着改变。(顾名思义,view仅仅是改变了了对这个张量量的观察⻆角度)
x += 1
y

tensor([[1.3654, 1.4571, 1.2273, 1.0126, 1.1949],
        [1.8327, 1.5999, 1.3840, 1.8391, 1.9840],
        [1.6709, 1.9550, 1.3656, 1.6259, 1.7896]])

In [41]:
# 如何做到深拷贝？
y = x.clone().view(-1, 5)
x += 1
print(x)
print(y)

tensor([[2.3654, 2.4571, 2.2273],
        [2.0126, 2.1949, 2.8327],
        [2.5999, 2.3840, 2.8391],
        [2.9840, 2.6709, 2.9550],
        [2.3656, 2.6259, 2.7896]])
tensor([[1.3654, 1.4571, 1.2273, 1.0126, 1.1949],
        [1.8327, 1.5999, 1.3840, 1.8391, 1.9840],
        [1.6709, 1.9550, 1.3656, 1.6259, 1.7896]])


In [44]:
# 另外一一个常用用的函数就是 item() , 它可以将一一个标量量 Tensor 转换成一一个Python number:
x_single = torch.randn(1, 1)
print(x_single)
print(x_single.item())

tensor([[-0.7962]])
-0.7962486743927002


In [46]:
# 广播机制
x1 = torch.arange(1, 3).view(1, 2)
y1 = torch.arange(1, 4).view(3, 1)
print(x1)
print(y1)
print(x1 + y1)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [51]:
# Tensor 转 NumPy
x1 = torch.ones(5)
y1 = x1.numpy()
print(x1, y1)
x1 += 1
print(x1, y1)
y1 += 1
print(x1, y1)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]
False


In [57]:
# NumPy数组转 Tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)
a += 1
print(a, b)
b += 1
print(a, b)
# 深拷贝
c = torch.tensor(a)
a += 1
print(a, c)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [62]:
# TENSOR ON GPU
if torch.cuda.is_available():
    device = torch.device('cuda') # GPU
    yy = torch.ones_like(x, device=device) # 直接创建一个在GPU上的Tensor
    x = x.to(device) # 等价于 to('cuda')
    z = x + yy
    print(z)
    print(z.to('cpu'), torch.double)

tensor([[3.3654, 3.4571, 3.2273],
        [3.0126, 3.1949, 3.8327],
        [3.5999, 3.3840, 3.8391],
        [3.9840, 3.6709, 3.9550],
        [3.3656, 3.6259, 3.7896]], device='cuda:0')
tensor([[3.3654, 3.4571, 3.2273],
        [3.0126, 3.1949, 3.8327],
        [3.5999, 3.3840, 3.8391],
        [3.9840, 3.6709, 3.9550],
        [3.3656, 3.6259, 3.7896]]) torch.float64
