In [1]:
import torch
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import time
import sys
import numpy as np
sys.path.append('../') # 为了导入library里面的函数包
import library.d2lzh_pytorch as d2l

#### 代码解释在P67

In [5]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(X.sum(dim=0, keepdim=True))
print(X.sum(dim=1, keepdim=True))

tensor([[5, 7, 9]])
tensor([[ 6],
        [15]])


#### 代码解释在P67

In [15]:
def softmax(X):
    X_exp = X.exp()
    partition = X_exp.sum(dim=1, keepdim=True)
    return X_exp / partition # 这里使用到了广播机制

In [17]:
X = torch.rand(2, 5)
X_prob = softmax(X)
print(X)
print(X_prob, '\n', X_prob.sum(dim=1, keepdim=True))

tensor([[0.2753, 0.7576, 0.9176, 0.1257, 0.7265],
        [0.5244, 0.7635, 0.4377, 0.7681, 0.1285]])
tensor([[0.1438, 0.2330, 0.2734, 0.1239, 0.2259],
        [0.1947, 0.2473, 0.1785, 0.2484, 0.1311]]) 
 tensor([[1.],
        [1.]])
